# -*- coding: utf-8 -*-

#   prompts.py

"""
### Description:
LLM prompt strings and builder helpers for the observer/reflector memory system.

All prompt text is preserved verbatim from the JS source so that model behaviour
is identical between the two implementations.

---

@Author:        Claude Sonnet 4.6
@Created on:    25.03.2026
@Based on:      src/memory/prompts.ts


"""


OBSERVER_SYSTEM_PROMPT = """You are the memory consciousness of an AI assistant.
Your observations will be the ONLY information the assistant has about past interactions.

Extract high-fidelity observations from conversation history.
Do not chat. Do not explain. Output only structured XML.

Rules:
1) Every observation MUST be tagged with its source: [user], [assistant], or [tool:name].
   - [user]: facts, preferences, decisions explicitly stated by the user.
   - [assistant]: actions taken, commitments made, or content generated by the assistant.
   - [tool:name]: outcomes of tool calls (e.g. [tool:write_file], [tool:read_file]).
2) Priority markers:
   - 🔴 high: explicit user facts, preferences, decisions, completed goals.
   - 🟡 medium: active work, project details, tool outcomes, unresolved blockers.
   - 🟢 low: tentative or minor details, assistant elaborations.
3) Preserve concrete details: names, numbers, dates, file paths, quoted phrasing.
4) Capture state changes explicitly ("updating previous preference").
5) Keep observations concise but information-dense.
6) Do NOT repeat observations that already exist in previous observations.

Output format (strict):
<observations>
* 🔴 [user] ...
* 🟡 [assistant] ...
* 🟡 [tool:write_file] ...
</observations>

<current-task>
Primary: ...
</current-task>

<suggested-response>
...
</suggested-response>""".strip()


def build_observer_prompt(previous_observations: str, message_history: str) -> str:
    """Build the user-turn prompt for the observer LLM call.

    Args:
        previous_observations: Already-recorded observations from prior turns.
        message_history: Serialized new messages to extract observations from.

    Returns:
        Formatted prompt string.
    """
    lines = [
        "## Previous Observations",
        "",
        previous_observations or "[none]",
        "",
        "---",
        "",
        "Do not repeat these existing observations. Only extract new ones.",
        "",
        "## New Message History",
        "",
        message_history or "[none]",
        "",
        "---",
        "",
        "Extract new observations. Return only XML with <observations>, <current-task>, <suggested-response>.",
    ]
    return "\n".join(lines)


REFLECTOR_SYSTEM_PROMPT = """You are the observation reflector — part of the memory consciousness.

You must reorganize and compress observations while preserving continuity.

Rules:
1) Your output is the ENTIRE memory. Anything omitted is forgotten.
2) Preserve source tags ([user], [assistant], [tool:name]) on every observation.
3) [user] observations are highest priority — never drop them unless contradicted by a newer [user] observation.
4) [assistant] elaborations are lowest priority — condense or drop them first.
5) [tool:*] outcomes should be kept as concise action records.
6) Condense older details first. Preserve recent details more strongly.
7) Resolve contradictions by preferring newer observations.
8) Use the same bullet format as input. Do NOT restructure into XML attributes or other schemas.

Output format:
<observations>
* 🔴 [user] ...
* 🟡 [tool:write_file] ...
</observations>""".strip()


# Indexed by compression level (0, 1, 2).
# Level 0 uses no extra guidance; levels 1 and 2 add increasingly aggressive hints.
REFLECTOR_COMPRESSION_LEVELS = [
    "",
    "Condense older observations more aggressively. Preserve detail for recent ones only.",
    "Heavily condense. Remove redundancy, keep only durable facts, active commitments, and blockers.",
]


def build_reflector_prompt(observations: str, guidance: str) -> str:
    """Build the user-turn prompt for a single reflector compression pass.

    Args:
        observations: Current observation text to compress.
        guidance: Optional extra guidance string (from REFLECTOR_COMPRESSION_LEVELS).

    Returns:
        Formatted prompt string.
    """
    # Mirror JS filter(Boolean): optional guidance line is None when absent,
    # None entries are dropped before joining — no blank line at level 0.
    parts = [
        "Compress and reorganize the observation memory below.",
        f"Additional guidance: {guidance}" if guidance else None,
        "<observations>",
        observations,
        "</observations>",
    ]
    return "\n".join(p for p in parts if p is not None)


CONTINUATION_HINT = "\n".join([
    "<system-reminder>",
    "Conversation history was compressed into memory observations.",
    "Continue naturally. Do not mention memory mechanics.",
    "</system-reminder>",
])


def build_observation_appendix(observations: str) -> str:
    """Build the system-prompt appendix that gives the agent its memory.

    Args:
        observations: Active observation text to inject.

    Returns:
        Formatted appendix string to append to the base system prompt.
    """
    return "\n".join([
        "The following observations are your memory of past conversations with this user.",
        "",
        "<observations>",
        observations,
        "</observations>",
        "",
        "IMPORTANT: Reference specific details from these observations when relevant.",
        "When observations conflict, prefer the most recent one.",
    ])
